name: repository-1
version: 2.0.2
versioned_at: 2026-10-08 17:22
description: Reusable source repository conventions.
entrypoint: README.md
dependencies:
- name: meta
  version: 2.0.2
  constraint: compatible
