name: repository-1
version: 3.0.0
versioned_at: 2026-10-08 17:44
description: Reusable source repository conventions.
entrypoint: README.md
dependencies:
- name: meta
  version: 2.0.2
  constraint: compatible
